apiVersion: v1
kind: Service
metadata:
  name: Ryhma2-service
spec:
  selector:
    app: ecsdemo-frontend
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 5000



#Lisätäänkö tällä LoadBalancer vaan?
#Mikä on Servicen tarkoitus?
#TÄTÄ EI TARVITSE MUUTA kuin apin nimi muuksi?